name: "CI/CD with Security Best Practices"

on:
  push:
    branches:
    - stable
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Build Docker image for local environment
    - name: Build Docker image using docker-compose.local.yml
      run: docker-compose -f docker-compose.local.yml build | tee docker-build-log.txt

    # Scan Docker image with Docker Scout
    - name: Scan with Docker Scout
      run: |
        docker run --rm \
        -v /var/run/docker.sock:/var/run/docker.sock \
        docker/scout:latest \
        scout brokencrystals:${{ github.sha }} --output scout-report.html

    - name: Scan Docker Image with Trivy
      # Scan Docker image with Trivy
      run: |
        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image brokencrystals:${{ github.sha }} \
        --format template --template "@contrib/html.tpl" -o trivy-scan-report.html

    - name: Log in to Docker Hub
      # Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

    # Push Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: docker push docker.io/ziemieu86/brokencrystals:${{ github.sha }}

    # Run OWASP ZAP for DAST
    - name: Run OWASP ZAP DAST
      run: |
        docker run -v $(pwd):/zap/wrk/:rw --network="host" owasp/zap2docker-stable zap-baseline.py \
        -t http://localhost:3000 -r owasp-zap-dast-report.html

    - name: Upload Docker Scout Report
      uses: actions/upload-artifact@v3
      with:
        name: docker-scout-report
        path: scout-report.html

    - name: Upload Trivy Docker Scan Report
      uses: actions/upload-artifact@v3
      with:
        name: trivy-scan-report
        path: trivy-scan-report.html

    - name: Upload OWASP ZAP DAST Report
      uses: actions/upload-artifact@v3
      with:
        name: owasp-zap-dast-report
        path: owasp-zap-dast-report.html

    - name: Upload Docker Build Log
      uses: actions/upload-artifact@v3
      with:
        name: docker-build-log
        path: docker-build-log.txt

# # Commit Scan Results to Repo
# - name: Commit Scan Reports
#   run: |
#     git config --global user.email "ci-bot@mycompany.com"
#     git config --global user.name "CI Bot"
#     git checkout ${{ github.ref }}
#     git add scout-report.html trivy-scan-report.html owasp-zap-dast-report.html docker-build-log.txt
#     git commit -m "Add CI/CD scan results and build logs"
#     git push
